### ISSUE TITLE
Dynamizer

### ISSUE THREAD

**Issue by jiann** [opengeospatial/ets-citygml30-part2#11]

**Comment by dstenger** [comment]
Abstract Test 26: Same as documented in https://github.com/opengeospatial/ets-citygml30-part2/issues/8#issuecomment-2165139786 for abstract test 21.

Abstract Test 27: Third bullet point is not implemented.

**Comment by dstenger** [comment]
Both remarks are covered by new issues:
* https://github.com/opengeospatial/ets-citygml30-part2/issues/34
* https://github.com/opengeospatial/ets-citygml30-part2/issues/35

Thus, this issue can be closed.
