### ISSUE TITLE
Transportation

### ISSUE THREAD

**Issue by jiann** [opengeospatial/ets-citygml30-part2#16]

**Comment by dstenger** [comment]
Abstract Test 34: It is just tested if there is a xlink:href attribute present but not if it references to a TrafficSpace element.

Abstract Test 35: Same as documented in https://github.com/opengeospatial/ets-citygml30-part2/issues/17#issuecomment-2165111933.

**Comment by dstenger** [comment]
Both remarks are covered by new issues:
* https://github.com/opengeospatial/ets-citygml30-part2/issues/33
* https://github.com/opengeospatial/ets-citygml30-part2/issues/34

Thus, this issue can be closed.
