### ISSUE TITLE
Acquire sample CityGML3.0 GML files

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ets-citygml30-part2#2]
We need to obtain sample CityGML3.0 GML files.

**Comment by ghobona** [comment]
[Here](https://github.com/opengeospatial/developer-events/tree/master/2023/Open-Standards-Code-Sprint/citygml/safe-software) is a sample file from FME used at the recent Open Standards Code Sprint.

Cc: @deanhintz

**Comment by ghobona** [comment]
The examples from the SWG are [here](https://github.com/opengeospatial/CityGML3.0-GML-Encoding/tree/main/resources/examples).

**Comment by ghobona** [comment]
Examples folder shared in December 2023, so closing the Issue.

**Comment by jiann** [comment]
| Module | Example |
|--------|--------|
Global #3 |   |
Core #4 | [CityGML3.0-GML-Encoding](https://github.com/opengeospatial/CityGML3.0-GML-Encoding/tree/main/resources/examples/Core)
Appearance #5 |  |
Bridge #6 |  |
Building #7 | [CityGML3.0-GML-Encoding](https://github.com/opengeospatial/CityGML3.0-GML-Encoding/tree/main/resources/examples/Building) [CityGML3.0-GML-Encoding](https://github.com/opengeospatial/CityGML3.0-GML-Encoding/tree/main/resources/examples/Examples-from-CityGML-2.0/building/CityGMLv3) [Open-Standards-Code-Sprint](https://github.com/opengeospatial/developer-events/tree/master/2023/Open-Standards-Code-Sprint/citygml/safe-software)
CityFurniture #9 |   |
CityObjectGroup #8 |  |
Construction #10 | [Open-Standards-Code-Sprint](https://github.com/opengeospatial/developer-events/tree/master/2023/Open-Standards-Code-Sprint/citygml/safe-software) [CityGML3.0-GML-Encoding](https://github.com/opengeospatial/CityGML3.0-GML-Encoding/blob/main/resources/examples/XLink-examples/1_SimpleBuilding/CityGML_3.gml) |  
Dynamizer #11 | [CityGML3.0-GML-Encoding](https://github.com/opengeospatial/CityGML3.0-GML-Encoding/tree/main/resources/examples/Dynamizer)
Generics #12 | [Open-Standards-Code-Sprint](https://github.com/opengeospatial/developer-events/tree/master/2023/Open-Standards-Code-Sprint/citygml/safe-software)
LandUse #13 |  |
PointCloud #14 |  |
Relief #15 |  |
Transportation #16 | [CityGML3.0-GML-Encoding](https://github.com/opengeospatial/CityGML3.0-GML-Encoding/tree/main/resources/examples/Transportation/Basic%20examples) [CityGML3.0-GML-Encoding](https://github.com/opengeospatial/CityGML3.0-GML-Encoding/tree/main/resources/examples/Transportation/Real-world%20examples/CityGML_3.0_transportation_data_from_OpenDRIVE) |  
Tunnel #17 |  |
Vegetation #18 |  |
Versioning #19 | [CityGML3.0-GML-Encoding](https://github.com/opengeospatial/CityGML3.0-GML-Encoding/tree/main/resources/examples/Versioning/Basic%20examples)
WaterBody #20 |  |
