### ISSUE TITLE
Implement of Requirement 6

### ISSUE THREAD

**Issue by jiann** [opengeospatial/ets-citygml30-part2#21]
Requirement 6

/req/global/alternativeaggregations

For referencing features from alternative aggregations:

A

Each feature belongs to a natural aggregation hierarchy and SHALL be stored inline this hierarchy.

B

Alternative aggregations SHALL NOT contain the feature inline but SHALL use an XLink to reference the feature.

https://docs.ogc.org/is/21-006r2/21-006r2.html

**Comment by dstenger** [comment]
-------- Weitergeleitete Nachricht --------
Betreff: 	Example data for CityGML 3.0 Part 2 test suite
Datum: 	Thu, 21 Mar 2024 11:59:31 +0100
Von: 	Dirk Stenger <stenger@lat-lon.de>
An: 	CityGML.swg@lists.ogc.org


All,

We are currently implementing a test suite for CityGML 3.0 Part 2.

Can anyone provide example data for "Requirement 6 /req/global/alternativeaggregations" which is about natural aggregations and alternative aggregations?

This would help us a lot to implement that test.

Kind regards,

Dirk
