### ISSUE TITLE
Create and update documentation

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-citygml30-part2#22]

**Comment by dstenger** [comment]
@jiann Can you please describe in the documentation that the test for requirement 6 (https://github.com/opengeospatial/ets-citygml30-part2/issues/21) is not implemented, yet?

**Comment by jiann** [comment]
@dstenger Do you mean to mention requirement 6 in index.adoc? If so, no problem. The documentation writing is in progress, and I will push it in about 2 or 3 days

**Comment by dstenger** [comment]
Yes, thank you!

**Comment by dstenger** [comment]
Please also update this site (appears when starting tests via Web Browser Interface):

![Bildschirmfoto vom 2024-04-18 16-02-11](https://github.com/opengeospatial/ets-citygml30-part2/assets/2989166/28e38413-5416-4468-a1f5-b7a82ae1a7de)

**Comment by dstenger** [comment]
Source code location is here: https://github.com/opengeospatial/ets-citygml30-part2/blob/develop-jiann/src/main/scripts/ctl/citygml30-part2-suite.ctl

**Comment by jiann** [comment]
commit: [#22 adding documentation in team engine's .ctl file](https://github.com/opengeospatial/ets-citygml30-part2/commit/7ed78abb7c1ee810d879f4436b4ab2a7c292484b)

![image](https://github.com/opengeospatial/ets-citygml30-part2/assets/17801899/2cef7ef0-9ce8-4608-89f7-812ed58e770d)
