### ISSUE TITLE
Unexpected test results

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-citygml30-part2#29]
Used files documented [here](https://github.com/opengeospatial/ets-citygml30-part2/issues/2#issuecomment-2068294903) to execute the test suite.

Test with [LocalCRS_CityGML3.gml](https://github.com/opengeospatial/CityGML3.0-GML-Encoding/blob/main/resources/examples/Core/LocalCRS_CityGML3.gml):
* All conformance classes fail.
* Core and Global tests are expected to pass.
* NullPointerException occurs and should be analyzed.
* Screenshot:
![Bildschirmfoto vom 2024-05-06 11-48-06](https://github.com/opengeospatial/ets-citygml30-part2/assets/2989166/f29604bc-45f7-40b7-8ca5-371b4a4615a0)

Test with [BuildingUnits_Storeys_xlink.gml](https://github.com/opengeospatial/CityGML3.0-GML-Encoding/blob/main/resources/examples/Building/BuildingUnits_Storeys_xlink.gml):
* All conformance classes fail.
* Core and Global tests are expected to pass.
* Building is also expected to pass but no test is executed.
* Screenshots:
![Bildschirmfoto vom 2024-05-06 11-51-40](https://github.com/opengeospatial/ets-citygml30-part2/assets/2989166/76fb0442-d24e-411f-8c69-f41bfa57e41f)
![Bildschirmfoto vom 2024-05-06 11-52-00](https://github.com/opengeospatial/ets-citygml30-part2/assets/2989166/dfd99b5d-03db-4019-98d2-d9882f41eb43)

**Comment by jiann** [comment]
The GlobalValidation.verifyCityGMLInstanceDoc() is working correctly now
![image](https://github.com/opengeospatial/ets-citygml30-part2/assets/17801899/b2911843-e7fd-4204-9655-eb2d8c31bbcc)
![image](https://github.com/opengeospatial/ets-citygml30-part2/assets/17801899/968515e5-e8e6-4c2f-8335-4f6f3f379c6d)

**Comment by dstenger** [comment]
@jiann If a "verify module" test (first test of any module) fails, all other tests of the module shall be skipped. Can you please check if that behavior can be implemented?
