### ISSUE TITLE
Global

### ISSUE THREAD

**Issue by jiann** [opengeospatial/ets-citygml30-part2#3]

**Comment by dstenger** [comment]
**Abstract Test 3:**

Spec states: "Geometries stored inline a space boundary are not redundantly stored as geometry of a space. If the geometry is stored with the space in addition, it references the geometry from the space boundary using XLinks."

Are the expressions "//*:spaceType" and "//*:SpaceBoundary" seem to be incorrect.
Please see definitions of
* space: https://docs.ogc.org/is/21-006r2/21-006r2.html#space-definition
* space boundary: https://docs.ogc.org/is/21-006r2/21-006r2.html#space-boundary-definition

**Abstract Test 4:**

Spec states: "Verify that LoDs are self-contained: Geometries are not shared between different LoDs using XLinks."

The code checks whether a single LoD element has two or more XLinks and fails if that is true.
The spec, however, describes that geometries shall not be shared between different LoDs.

**Abstract Test 5**

Spec states: "If two top-level features share a common geometry, the shared geometry is stored for each top-level feature separately."

This bullet point seems not to be tested by the implementation.

**Comment by dstenger** [comment]
Remarks were moved to a new issue:
* https://github.com/opengeospatial/ets-citygml30-part2/issues/36

Thus, this issue can be closed.
