### ISSUE TITLE
Improve schema validation tests

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-citygml30-part2#32]
Schema validation tests seem to not do a full schema validation (only a single element is checked).

An example how to implement a full schema validation can be found here: https://github.com/opengeospatial/ets-gml32/blob/master/src/main/java/org/opengis/cite/iso19136/data/XMLSchemaValidationTests.java

All tests requiring full schema validation shall be adjusted accordingly.

**Comment by dstenger** [comment]
@jiann Can you please check the description of this issue and if you need further information?

**Comment by jiann** [comment]
> Schema validation tests seem to not do a full schema validation (only a single element is checked).
> 
> An example how to implement a full schema validation can be found here: https://github.com/opengeospatial/ets-gml32/blob/master/src/main/java/org/opengis/cite/iso19136/data/XMLSchemaValidationTests.java
> 
> All tests requiring full schema validation shall be adjusted accordingly.

@dstenger 
The full schema will validate in [GlobalValidation.verifyCityGMLInstanceDoc()](https://github.com/opengeospatial/ets-citygml30-part2/blob/4835d93d13074fd822071789ff58e4d4b346dbc1/src/main/java/org/opengis/cite/citygml30part2/global/GlobalValidation.java#L25). It collects the namespaces defined in the XML file and binds them with the local XSD file and the XSD files are used to create a schema validator that validates multiple schemas together.

The document for this requirement is here : https://docs.ogc.org/is/21-006r2/21-006r2.html#gml-section

**Comment by dstenger** [comment]
Thank you for the clarification.
I confirm that this code executes the full schema validation and mark this issue with invalid.
