### ISSUE TITLE
Re-work implementations of Appearance tests

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-citygml30-part2#37]
**Abstract Test 11:**

Inheritance of gml:AbstractSurfaceType and gml:MultiSurface is not considered.

**Abstract Test 12:**

Expression `//app:textureCoordinates[@ring]` seems not to be correct (line 84).

[Spec](https://docs.ogc.org/is/21-006r2/21-006r2.html#_conformance_class_appearance) states: "...The textureCoordinates and ring properties of a TexCoordList element form pairs and their order is decisive...."

[Schema](https://schemas.opengis.net/citygml/appearance/3.0/appearance.xsd) states:
```
...
  <element name="TexCoordList" substitutionGroup="app:AbstractTextureParameterization" type="app:TexCoordListType">
    <annotation>
      <documentation>TexCoordList defines texture parameterization using texture coordinates.</documentation>
    </annotation>
  </element>
  <complexType name="TexCoordListType">
    <complexContent>
      <extension base="app:AbstractTextureParameterizationType">
        <sequence>
          <element maxOccurs="unbounded" name="textureCoordinates" type="gml:doubleList">
            <annotation>
              <documentation>Specifies the coordinates of texture used for parameterization. The texture coordinates are provided separately for each LinearRing of the surface geometry object.</documentation>
            </annotation>
          </element>
          <element maxOccurs="unbounded" name="ring" type="anyURI">
            <annotation>
              <documentation>Specifies the URIs that point to the LinearRings that are parameterized using the given texture coordinates.</documentation>
            </annotation>
          </element>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
...
```

Other expressions shall be checked as well.

**Abstract Test 13:**

Is not implemented.

**Comment by jiann** [comment]
Abstract Test 11:
Verify that surface data is only applied to surface geometries. The target property of a surface data element therefore only references a subtype of gml:AbstractSurfaceType or a gml:MultiSurface.

Need help to collect Inheritance of gml:AbstractSurfaceType and gml:MultiSurface

**Comment by dstenger** [comment]
Re-work of abstract test 11 was moved to https://github.com/opengeospatial/ets-citygml30-part2/issues/38.

**Comment by dstenger** [comment]
@jiann

**Abstract Test 12:**

I still see the expression "//app:textureCoordinates[@ring]". However, ring is a property and not an attribute. Can you please check this?

**Comment by dstenger** [comment]
Still, this expression is used in Test E.
@jiann Can you please check if that is correct?
