### ISSUE TITLE
 Abstract Test 11 /req/appearance/target

### ISSUE THREAD

**Issue by jiann** [opengeospatial/ets-citygml30-part2#38]
Abstract Test 11:
Verify that surface data is only applied to surface geometries. The target property of a surface data element therefore only references a subtype of gml:AbstractSurfaceType or a gml:MultiSurface.

Need help to collect Inheritance of gml:AbstractSurfaceType and gml:MultiSurface

**Comment by jiann** [comment]
The <app:target> will references a node's gml:id in it's text, we will assert is the node are exist or not and check it's node type, we need to collect the inheritance of gml:AbstractSurfaceType, gml:MultiSurface and store the name in a json file, so we can assert the node name are contains in the inheritance list.

The test are throw a SkipException for now.

**Comment by dstenger** [comment]
@jiann
gml:MultiSurface is already an element and no sub-types must be checked.
http://www.datypic.com/sc/niem21/t-gml32_AbstractSurfaceType.html lists possible sub-types of gml:AbstractSurfaceType.
Does this information help you to continue with the implementation?
