### ISSUE TITLE
Core

### ISSUE THREAD

**Issue by jiann** [opengeospatial/ets-citygml30-part2#4]

**Comment by dstenger** [comment]
Abstract Test 8: It is just tested if there is a xlink:href attribute present but not if it references to an AbstractCityObject element.

Abstract Test 9: Same as documented in https://github.com/opengeospatial/ets-citygml30-part2/issues/17#issuecomment-2165111933.

**Comment by dstenger** [comment]
Both remarks are covered by new issues:
* https://github.com/opengeospatial/ets-citygml30-part2/issues/33
* https://github.com/opengeospatial/ets-citygml30-part2/issues/34

Thus, this issue can be closed.
