### ISSUE TITLE
"Verify City GML Instance Doc" test finishes with unexpected error

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-citygml30-part2#40]
Used test file: [LocalCRS_CityGML3.gml](https://github.com/opengeospatial/ets-citygml30-part2/blob/develop-jiann/src/test/resources/LocalCRS_CityGML3.gml)

Screenshot from test run with Web Browser Interface:
![Bildschirmfoto vom 2024-07-17 19-24-25](https://github.com/user-attachments/assets/6e675807-3f77-4ddc-aa2a-b43fcc4adb91)

It is expected that the reference file is passing this test.

In addition, the failure message "null" is not understandable and shall be improved.

**Comment by dstenger** [comment]
Unfortunately, this error occurs again.
Further information: I uploaded the referenced file (see description) via the Web Browser Interface of TEAM Engine.
@jiann Can you please take a look at this?

**Comment by jiann** [comment]
@dstenger 
Could you provide the steps you executed to run the test? This source file is working successfully in my environment. I'm using the following commands:

1. `mvn clean install site -Pintegration-tests,docker` to create the Docker container.
2. `https://raw.githubusercontent.com/opengeospatial/ets-citygml30-part2/develop-jiann/src/test/resources/LocalCRS_CityGML3.gml` as the input.

<img width="965" alt="image" src="https://github.com/user-attachments/assets/f947ecfb-4d95-4265-8f53-e4d08b8a686a">

**Comment by dstenger** [comment]
@jiann In the second step, I do not use the URL but the upload button of the GUI.

**Comment by dstenger** [comment]
Error is not occurring anymore.
